spring:
  application:
    name: "clima-api"

  datasource:
    url: "jdbc:postgresql://localhost:5432/clima_db"
    username: "admin"
    password: "admin-api"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  web:
    resources:
      add-mappings: false

  flyway:
    enabled: true
    locations: classpath:db/migration

openweather:
  api:
    key: ${OPENWEATHER_API_KEY}
    url: https://api.openweathermap.org/data/2.5

springdoc:
  swagger-ui:
    path: /swagger-ui.html

